# Generated by Django 4.2.4 on 2023-08-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhryke_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='date edited'),
        ),
    ]
