# Generated by Django 4.2.4 on 2023-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhryke_app', '0002_alter_message_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date edited'),
        ),
    ]
