# Generated by Django 4.2.4 on 2023-08-23 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhryke_app', '0003_alter_message_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 23, 13, 56, 2, 368828), verbose_name='date published'),
        ),
    ]
